name: C++ Build and Test

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Compile C++ Code
        run: g++ main.cpp -o hello_world

      - name: Run Executable
        run: ./hello_world
